### ISSUE TITLE
25 Hz limtation

### ISSUE THREAD

**Issue by duncancarroll** [yoctopuce/Yocto-Visualization#1]
Hello!

Is it possible to allow > 25 Hz refresh in the widgets?

Thank you for the excellent products!

**Comment by yoctopuce** [comment]
Actually, the report frequency is stored in the devices, so just use the VirtualHub or the [command line API](www.yoctopuce.com/EN/libraries.php) to setup the sensor report frequency to a value higher than the ones allowed in the Yocto-Visualization UI, for instance
 
`ysensor.exe -s METEOMK2-1D0E02.temperature set_reportFrequency 100/s`

..and Yocto-Visualization will automatically try to refresh at the same rate , but don't be surprised if it can't keep up. 

Also make sure you understand how [Yoctopuce sensors internal sampling works](www.yoctopuce.com/EN/article/inner-workings-of-yoctopuce-sensors), on most Yoctopuce sensors there is no upside in setting  a report frequency higher than 25Hz.

**Comment by duncancarroll** [comment]
Ok, thank you!
